// <auto-generated />
namespace Solomon.WebUI.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddCheckPendingToProblem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCheckPendingToProblem));
        
        string IMigrationMetadata.Id
        {
            get { return "201502091709389_AddCheckPendingToProblem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
